export var StatusCode;
(function (StatusCode) {
    StatusCode[StatusCode["SUCCESS"] = 200] = "SUCCESS";
    StatusCode[StatusCode["CREATED"] = 201] = "CREATED";
    StatusCode[StatusCode["BAD_REQUEST"] = 400] = "BAD_REQUEST";
    StatusCode[StatusCode["UNAUTHENTICATED"] = 401] = "UNAUTHENTICATED";
    StatusCode[StatusCode["FORBIDDEN"] = 403] = "FORBIDDEN";
    StatusCode[StatusCode["NOT_FOUND"] = 404] = "NOT_FOUND";
    StatusCode[StatusCode["UNPROCESSABLE_ENTITY"] = 422] = "UNPROCESSABLE_ENTITY";
    StatusCode[StatusCode["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
    StatusCode[StatusCode["BAD_GATEWAY"] = 502] = "BAD_GATEWAY";
})(StatusCode || (StatusCode = {}));
export var ErrorDescription;
(function (ErrorDescription) {
    ErrorDescription["INVALID_INPUT"] = "Input provided is not valid.";
    ErrorDescription["INVALID_PAYLOAD"] = "Payload provided does not satisfy our request body requirements.";
    ErrorDescription["MAINTENANCE"] = "Server module under maintenance";
    ErrorDescription["FORBIDDEN"] = "User does not have the permission to access or create resource";
    ErrorDescription["QUERY_EXCEPTION"] = "Malformed query founds in database operations.";
    ErrorDescription["UNEXPECTED_ERROR"] = "An unexpected events occurs on database transactions or server operations. ";
    ErrorDescription["UNHANDLED_EXCEPTION"] = "Errors generate from operations without exception handling.";
    ErrorDescription["CLIENT_EXCEPTION"] = "Client made an invalid request.";
    ErrorDescription["SERVER_EXCEPTION"] = "Server failed to fulfill a request. ";
    ErrorDescription["UNAUTHORIZED"] = "You have no permission access to the resources";
    ErrorDescription["UNAUTHENTICATED"] = "Unable to authenticated with the provided credentials";
    ErrorDescription["API_KEY_INVALID"] = "API Key invalid";
    ErrorDescription["NOT_FOUND"] = "Record not found";
    ErrorDescription["BAD_GATEWAY"] = "Unknown error occurs";
    ErrorDescription["INVALID_TOKEN_FORMAT"] = "The token provided in your request is not in the expected format.";
    ErrorDescription["IMPLEMENTATION_EXCEPTION"] = "It appears that there is an issue with the implementation of a specific feature in the software";
    ErrorDescription["UNIMPLEMENTED_EXCEPTION"] = "It appears that the feature you're attempting to access is not yet implemented in the software";
    ErrorDescription["CONFIG_EXCEPTION"] = "It seems that there is an issue with the configuration settings of the software";
    ErrorDescription["INVALID_ARGUMENT"] = "It seems that there is an issue with the argument of the function call";
    ErrorDescription["CACHE_EXCEPTION"] = "It seems that there is an issue with the cache implementation of the function call";
    ErrorDescription["INVALID_CREDENTIAL"] = "The credential provided in your request is not valid.";
})(ErrorDescription || (ErrorDescription = {}));
export var ErrorCode;
(function (ErrorCode) {
    ErrorCode["CACHE_EXCEPTION"] = "CACHE_EXCEPTION";
    ErrorCode["INVALID_TOKEN_FORMAT"] = "INVALID_TOKEN_FORMAT";
    ErrorCode["INVALID_CREDENTIAL"] = "INVALID_CREDENTIAL";
    ErrorCode["INVALID_INPUT"] = "INVALID_INPUT";
    ErrorCode["INVALID_PAYLOAD"] = "INVALID_PAYLOAD";
    ErrorCode["MAINTENANCE"] = "MAINTENANCE";
    ErrorCode["FORBIDDEN"] = "FORBIDDEN";
    ErrorCode["QUERY_EXCEPTION"] = "QUERY_EXCEPTION";
    ErrorCode["UNEXPECTED_ERROR"] = "UNEXPECTED_ERROR";
    ErrorCode["UNHANDLED_EXCEPTION"] = "UNHANDLED_EXCEPTION";
    ErrorCode["IMPLEMENTATION_EXCEPTION"] = "IMPLEMENTATION_EXCEPTION";
    ErrorCode["UNIMPLEMENTED_EXCEPTION"] = "UNIMPLEMENTED_EXCEPTION";
    ErrorCode["CLIENT_EXCEPTION"] = "CLIENT_EXCEPTION";
    ErrorCode["SERVER_EXCEPTION"] = "SERVER_EXCEPTION";
    ErrorCode["UNAUTHORIZED"] = "UNAUTHORIZED";
    ErrorCode["UNAUTHENTICATED"] = "UNAUTHENTICATED";
    ErrorCode["API_KEY_INVALID"] = "API_KEY_INVALID";
    ErrorCode["NOT_FOUND"] = "NOT_FOUND";
    ErrorCode["BAD_GATEWAY"] = "BAD_GATEWAY";
    ErrorCode["CONFIG_EXCEPTION"] = "CONFIG_EXCEPTION";
    ErrorCode["INVALID_ARGUMENT"] = "INVALID_ARGUMENT";
})(ErrorCode || (ErrorCode = {}));
//# sourceMappingURL=response.enum.js.map